package data
// This file is automatically generated by pgxdata.

import (
  "strings"

  "github.com/jackc/pgx"
)

type IPTypes struct {
  ID Int32
  IPInet IPNet
  IPCidr IPNet
}

const countIPTypesSQL = `select count(*) from "ip_types"`

func CountIPTypes(db Queryer) (int64, error) {
  var n int64
  err := prepareQueryRow(db, "pgxdataCountIPTypes", countIPTypesSQL).Scan(&n)
  return n, err
}

const SelectAllIPTypesSQL = `select
  "id",
  "ip_inet",
  "ip_cidr"
from "ip_types"`

func SelectAllIPTypes(db Queryer) ([]IPTypes, error) {
  var rows []IPTypes

  dbRows, err := prepareQuery(db, "pgxdataSelectAllIPTypes", SelectAllIPTypesSQL)
  if err != nil {
    return nil, err
  }

  for dbRows.Next() {
    var row IPTypes
    dbRows.Scan(
&row.ID,
    &row.IPInet,
    &row.IPCidr,
    )
    rows = append(rows, row)
  }

  if dbRows.Err() != nil {
    return nil, dbRows.Err()
  }

  return rows, nil
}

const selectIPTypesByPKSQL = `select
  "id",
  "ip_inet",
  "ip_cidr"
from "ip_types"
where "id"=$1`

func SelectIPTypesByPK(
  db Queryer,
  id int32,
) (*IPTypes, error) {
  var row IPTypes
  err := prepareQueryRow(db, "pgxdataSelectIPTypesByPK", selectIPTypesByPKSQL, id).Scan(
&row.ID,
    &row.IPInet,
    &row.IPCidr,
    )
  if err == pgx.ErrNoRows {
    return nil, ErrNotFound
  } else if err != nil {
    return nil, err
  }

  return &row, nil
}

func InsertIPTypes(db Queryer, row *IPTypes) error {
  args := pgx.QueryArgs(make([]interface{}, 0, 3))

  var columns, values []string

  row.ID.addInsert(`id`, &columns, &values, &args)
  row.IPInet.addInsert(`ip_inet`, &columns, &values, &args)
  row.IPCidr.addInsert(`ip_cidr`, &columns, &values, &args)


  sql := `insert into "ip_types"(` + strings.Join(columns, ", ") + `)
values(` + strings.Join(values, ",") + `)
returning "id"
  `

  psName := preparedName("pgxdataInsertIPTypes", sql)

  return prepareQueryRow(db, psName, sql, args...).Scan(&row.ID)
}

func UpdateIPTypes(db Queryer,
  id int32,
  row *IPTypes,
) error {
  sets := make([]string, 0, 3)
  args := pgx.QueryArgs(make([]interface{}, 0, 3))

  row.ID.addUpdate(`id`, &sets, &args)
  row.IPInet.addUpdate(`ip_inet`, &sets, &args)
  row.IPCidr.addUpdate(`ip_cidr`, &sets, &args)


  if len(sets) == 0 {
    return nil
  }

  sql := `update "ip_types" set ` + strings.Join(sets, ", ") + ` where `  + `"id"=` + args.Append(id)

  psName := preparedName("pgxdataUpdateIPTypes", sql)

  commandTag, err := prepareExec(db, psName, sql, args...)
  if err != nil {
    return err
  }
  if commandTag.RowsAffected() != 1 {
    return ErrNotFound
  }
  return nil
}

func DeleteIPTypes(db Queryer,
  id int32,
) error {
  args := pgx.QueryArgs(make([]interface{}, 0, 1))

  sql := `delete from "ip_types" where `  + `"id"=` + args.Append(id)

  commandTag, err := prepareExec(db, "pgxdataDeleteIPTypes", sql, args...)
  if err != nil {
    return err
  }
  if commandTag.RowsAffected() != 1 {
    return ErrNotFound
  }
  return nil
}

