// This file is automatically generated.
package data

import (
  "strings"

  "github.com/jackc/pgx"
)

type WidgetRow struct {
  ID Int64
  Name String
  Weight Int16
}

func CountWidgetRow(db Queryer) (int64, error) {
  var n int64
  sql := `select count(*) from "widget"`
  err := db.QueryRow(sql).Scan(&n)
  return n, err
}

func SelectAllWidgetRow(db Queryer) ([]WidgetRow, error) {
  sql := `select
  "id",
  "name",
  "weight"
from "widget"`

  var rows []WidgetRow

  dbRows, err := db.Query(sql)
  if err != nil {
    return nil, err
  }

  for dbRows.Next() {
    var row WidgetRow
    dbRows.Scan(
&row.ID,
    &row.Name,
    &row.Weight,
    )
    rows = append(rows, row)
  }

  if dbRows.Err() != nil {
    return nil, dbRows.Err()
  }

  return rows, nil
}

func SelectWidgetRowByID(db Queryer, id int32) (*WidgetRow, error) {
  sql := `select
  "id",
  "name",
  "weight"
from "widget"
where id=$1`

  var row WidgetRow
  err := db.QueryRow(sql, id).Scan(
&row.ID,
    &row.Name,
    &row.Weight,
    )
  if err == pgx.ErrNoRows {
    return nil, ErrNotFound
  } else if err != nil {
    return nil, err
  }

  return &row, nil
}

func InsertWidgetRow(db Queryer, row *WidgetRow) error {
  args := pgx.QueryArgs(make([]interface{}, 0, 3))

  var columns, values []string

  row.ID.addInsert(`id`, &columns, &values, &args)
  row.Name.addInsert(`name`, &columns, &values, &args)
  row.Weight.addInsert(`weight`, &columns, &values, &args)


  sql := `insert into "widget"(` + strings.Join(columns, ", ") + `)
values(` + strings.Join(values, ",") + `)
returning id
  `

  return db.QueryRow(sql, args...).Scan(&row.ID)
}

func UpdateWidgetRow(db Queryer, id int32, row *WidgetRow) error {
  sets := make([]string, 0, 3)
  args := pgx.QueryArgs(make([]interface{}, 0, 3))

  row.ID.addUpdate(`id`, &sets, &args)
  row.Name.addUpdate(`name`, &sets, &args)
  row.Weight.addUpdate(`weight`, &sets, &args)


  if len(sets) == 0 {
    return nil
  }

  sql := `update "widget" set ` + strings.Join(sets, ", ") + ` where id=` + args.Append(id)

  commandTag, err := db.Exec(sql, args...)
  if err != nil {
    return err
  }
  if commandTag.RowsAffected() != 1 {
    return pgx.ErrNoRows
  }
  return nil
}

func DeleteWidgetRow(db Queryer, id int32) error {
  sql := `delete from "widget" where id=$1`

  commandTag, err := db.Exec(sql, id)
  if err != nil {
    return err
  }
  if commandTag.RowsAffected() != 1 {
    return pgx.ErrNoRows
  }
  return nil
}

